DEMO_HOLDINGS = [
    {
        "symbol": "RELIANCE",
        "company": "Reliance Industries",
        "quantity": 18,
        "average_price": 1284.50,
        "current_price": 1461.20,
        "sector": "Energy",
        "market_cap": "Large Cap",
    },
    {
        "symbol": "HDFCBANK",
        "company": "HDFC Bank",
        "quantity": 20,
        "average_price": 1698.00,
        "current_price": 1934.70,
        "sector": "Financials",
        "market_cap": "Large Cap",
    },
    {
        "symbol": "TCS",
        "company": "Tata Consultancy Services",
        "quantity": 8,
        "average_price": 3975.00,
        "current_price": 3842.60,
        "sector": "Technology",
        "market_cap": "Large Cap",
    },
    {
        "symbol": "SUNPHARMA",
        "company": "Sun Pharmaceutical",
        "quantity": 14,
        "average_price": 1540.00,
        "current_price": 1738.40,
        "sector": "Healthcare",
        "market_cap": "Large Cap",
    },
    {
        "symbol": "TMPV",
        "company": "Tata Motors Passenger Vehicles Limited",
        "quantity": 30,
        "average_price": 597.62,
        "current_price": 559.30,
        "sector": "Automobile",
        "market_cap": "Large Cap",
    },
    {
        "symbol": "TMCV",
        "company": "Tata Motors Limited (Commercial Vehicles)",
        "quantity": 30,
        "average_price": 270.38,
        "current_price": 253.05,
        "sector": "Automobile",
        "market_cap": "Large Cap",
    },
    {
        "symbol": "TRENT",
        "company": "Trent Limited",
        "quantity": 4,
        "average_price": 5230.00,
        "current_price": 5748.10,
        "sector": "Consumer",
        "market_cap": "Large Cap",
    },
    {
        "symbol": "COFORGE",
        "company": "Coforge Limited",
        "quantity": 5,
        "average_price": 6190.00,
        "current_price": 6765.00,
        "sector": "Technology",
        "market_cap": "Mid Cap",
    },
    {
        "symbol": "KPITTECH",
        "company": "KPIT Technologies",
        "quantity": 12,
        "average_price": 1425.00,
        "current_price": 1318.90,
        "sector": "Technology",
        "market_cap": "Mid Cap",
    },
]
